development:
  adapter: postgresql
  encoding: unicode
  database: bb_development
  pool: 5
  username: businessbites
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: bb_test
  pool: 5
  username: businessbites
  password: 