# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 97632332a1e324d0a2e9a9ebe82ea797399f45294c95820397e2add1c6833db64f292196bb90eec7b44fccdb5a41e6b8463c85a8699b529d16a711cdc369448e

test:
  secret_key_base: cd0e02c332a5aa8c94ee1e9fa419314ee7e2e923690e8058d07c34f69dd402e223ec66c06c02bfead05982882bf9a1c35ea4d9a974e4db01a2b8e16654d19162

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
